name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity."
          stale-issue-label: "stale"
          days-before-stale: 30   # mark stale after 30 days
          days-before-close: 7    # close 7 days after stale
